language: java

env:
- PLAY_VERSION=2.2.6

before_script:
- wget http://downloads.typesafe.com/play/${PLAY_VERSION}/play-${PLAY_VERSION}.zip
- unzip -q play-${PLAY_VERSION}.zip
script:
-  mvn play2:run
